version: 2.1

orbs:
  rn: react-native-community/react-native@5.5.0
  windows: circleci/windows@2.4.0

jobs:
  checkout_code:
    executor: rn/linux_js
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  verify:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Lint JS Code (ESLint)
          command: yarn run validate:eslint
      - run:
          name: Flow
          command: yarn run validate:flow

  test:
    executor: rn/linux_js
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Run unit tests with Jest
          command: yarn run test:jest

  build_example_windows:
    executor:
      name: windows/default
      shell: powershell
    steps:
      - checkout
      - run:
          name: Install examples
          command: cd src; yarn install; cd ../example; yarn install --force --frozen-lockfile
      - run:
          name: "Restore NuGet packages for Components"
          command: nuget restore .\example\windows\SliderTestWindows.sln
      - run:
          name: "Restore .NET dependencies"
          command: msbuild -t:restore .\example\windows\SliderTestWindows.sln
      - run:
          name: Build example Windows
          command: cd example; npx react-native run-windows --no-packager --no-launch --arch x64 --logging --no-deploy

  build_example_ios:
    executor: rn/macos
    steps:
      - checkout
      - run:
          name: Install deps
          command: cd src && yarn install && cd ../example && yarn install --force --frozen-lockfile
      - run:
          name: Install Pods
          command: cd example && npx pod-install
      - run:
          name: Build the iOS example project
          command: cd example/ios && export RCT_NO_LAUNCH_PACKAGER=true && xcodebuild -workspace example.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11' -scheme example -parallelizeTargets -configuration Debug -derivedDataPath build  -UseModernBuildSystem=YES

  # To be uncommented as a part of https://github.com/react-native-community/react-native-slider/issues/34
  # publish:
  #   executor: rn/linux_js
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - rn/yarn_install
  #     - run:
  #         name: Publish to NPM
  #         command: yarn ci:publish

workflows:
  slider-full-ci:
    jobs:
      - checkout_code
      - verify:
          requires:
            - checkout_code
      - test:
          requires:
            - verify
      - build_example_windows:
          requires:
            - verify
      - rn/android_build:
          name: build_android_debug
          project_path: "example/android"
          build_type: debug
          requires:
            - verify
      - build_example_ios:
          requires:
            - verify
      # - publish:
      #     requires:
      #       - analyse
      #       - rn/android_test
      #       - rn/ios_build_and_test
      #     filters:
      #       branches:
      #         only: master
